server:
  port: 8083
  servlet:
    context-path: /file
spring:
  application:
    name: szcloud-upload-service
  servlet:
    multipart:
      max-file-size: 5MB
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.60:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"


### 不同文件类型上传的地址
file.resource:
  base: /home/bytool/file
  excle-path: ${file.resource.base}/excle/
  word-path: ${file.resource.base}/word/
  pdf-path: ${file.resource.base}/pdf/
  pic-path: ${file.resource.base}/pic/