server:
  port: 8083
  servlet:
    context-path: /pokemon
spring:
  application:
    name: szcloud-upload-service
  servlet:
    multipart:
      max-file-size: 5MB
  profiles:
    active: dev
    include:
      - file
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.60:8848


management:
  endpoints:
    web:
      exposure:
        include: "*"
