server:
  port: 8083
spring:
  application:
    name: szcloud-upload-service
  servlet:
    multipart:
      max-file-size: 5MB
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.60:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"