#datasource:
#  druid:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initial-size: 1
#    max-active: 20
#    min-idle: 1
#    test-on-borrow: true
#    test-while-idle: true
#    time-between-eviction-runs-millis: 60000
#    url: jdbc:mysql://192.168.5.120:3306/ditto?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
#    username: root
#    password: 123456
#    validation-query: SELECT 1 FROM DUAL
spring:
  redis:
    database: 1
    host: 192.168.5.120
    port: 6379
    cache:
      redis:
        time-to-live: 60000
      jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

profile: dev
server:
  port: 8888
