datasource:
  druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 1
    max-active: 20
    min-idle: 1
    password: 123456
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    url: jdbc:mysql://192.168.40.14:3306/wx_matter_poly?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    validation-query: SELECT 1 FROM DUAL
spring:
  redis:
    database: 5
    host: 192.168.40.14
    port: 6379
    cache:
      redis:
        time-to-live: 60000
      jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

profile: dev
server:
  port: 8040

#公共参数
common.resource:
  #照片访问地址
  pic-url: 'http://192.168.5.60:8040/mario/img/'
  #事项暴露地址
  matter-url: http://192.168.5.60:80